version: "3.8"
services:

 opensips_exporter:
    image: opensips_exporter:1.0
    container_name: opensips_exporter
    restart: always
    volumes:
           - /u01/docker-opensips248-tel/socket:/var/run/opensips
           - /etc/localtime:/etc/localtime:ro
    command: /usr/local/bin/opensips_exporter -protocol mi_datagram -socket /var/run/opensips/opensips.sock -addr 192.168.2.192:9737
    network_mode: "host"

